apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: gitImplementation
      value: libgit2
    - name: testing_pipeline_matching_labels 
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: java
    - name: scanning_source_policy
      value: scan-policy-relaxed
    - name: scanning_image_policy
      value: scan-policy-relaxed
  source:
    git:
      url: https://dev.azure.com/gorkemozlu-tanzu/tap/_git/tap
      ref:
        branch: main