#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
##kubectl create secret tls local-ca --key ca-no-pass.key --cert ca.crt -n cert-manager
---
apiVersion: v1
data:
  tls.crt: #@ base64.encode(data.values.ca_cert_data)
  tls.key: #@ base64.encode(data.values.ca_cert_key)
kind: Secret
metadata:
  creationTimestamp: null
  name: local-ca
  namespace: cert-manager
type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: local-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-wildcard
  namespace: tap-install
spec:
  secretName: tap-wildcard
  commonName: #@ "*.{}".format(data.values.ingress_domain)
  dnsNames:
    - #@ "*.{}".format(data.values.ingress_domain)
  issuerRef:
    name: local-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-wildcard
  namespace: tap-install
spec:
  delegations:
  - secretName: tap-wildcard
    targetNamespaces: ["*"]
