tap_install:
  values:
    shared:
      ingress_domain: tap.yldemotanzu.com
      ingress_issuer: local-issuer
      image_registry:
        project_path: harbor.yldemotanzu.com/tap-15
      ca_cert_data: |
        -----BEGIN CERTIFICATE-----
        MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
        iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
        cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
        BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
        MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
        BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
        ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
        VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
        AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
        TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
        eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
        oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
        Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
        uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
        BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
        +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
        A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
        CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
        LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
        BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
        bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
        L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
        ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
        7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
        H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
        RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
        xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
        sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
        l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
        6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
        LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
        yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
        00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
        -----END CERTIFICATE-----
    ceip_policy_disclosed: true
    profile: full
    supply_chain: basic
    ootb_supply_chain_basic:
      registry:
        server: harbor.yldemotanzu.com
        repository: tap-15/supplychain
      gitops:
        ssh_secret: git-secret
      maven:
        repository:
          url: https://nexus-80.tap.corp.com/repository/maven-central/
          secret_name: maven-credentials
    ootb_supply_chain_testing:
      registry:
        server: harbor.yldemotanzu.com
        repository: tap-15/supplychain
      gitops:
        ssh_secret: git-secret
      maven:
        repository:
          url: https://nexus-80.tap.corp.com/repository/maven-central/
          secret_name: maven-credentials
    ootb_supply_chain_testing_scanning:
      registry:
        server: harbor.yldemotanzu.com
        repository: tap-15/supplychain
      gitops:
        ssh_secret: git-secret
      maven:
        repository:
          url: https://nexus-80.tap.corp.com/repository/maven-central/
          secret_name: maven-credentials
    contour:
      envoy:
        service:
          type: LoadBalancer
    buildservice:
      kp_default_repository: harbor.yldemotanzu.com/tap-15/build
      kp_default_repository_username: admin
      exclude_dependencies: true
    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      ingressEnabled: "true"
      app_config:
        catalog:
          locations:
          - type: url
            target: https://github.com/MoSehsah/bank-demo/blob/main/catalog/catalog-info.yaml
        backend:
          reading:
            allow:
            - host: git.tap.corp.com
        auth:
          allowGuestAccess: true
          environment: development
          session:
            secret: secretvalue
          providers:
            oidc:
              development:
                clientId: tap-auth
                clientSecret: secretvalue
                metadataUrl: https://dex.tap.yldemotanzu.com/.well-known/openid-configuration
    cnrs:
      domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'
      ingress_issuer: local-issuer
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
    scanning:
      metadataStore:
        url: ""
    grype:
      targetImagePullSecret: scanner-secret-ref
      db:
        dbUpdateUrl: https://minio.tap.yldemotanzu.com/grype/databases/listing.json
    crossplane:
      registryCaBundleConfig:
        name: ca-bundle-config
        key: ca-bundle
    bitnami_services:
      mysql:
        helm_chart:
          repo: oci://harbor.yldemotanzu.com/bitnami/charts
          version: 9.8.1
          chart_pull_secret_ref:
            name: chart-pull
            namespace: default
          container_pull_secret_ref:
            name: container-pull
            namespace: default
      postgresql:
        helm_chart:
          repo: oci://harbor.yldemotanzu.com/bitnami/charts
          version: 12.3.1
          chart_pull_secret_ref:
            name: chart-pull
            namespace: default
          container_pull_secret_ref:
            name: container-pull
            namespace: default
      rabbitmq:
        helm_chart:
          repo: oci://harbor.yldemotanzu.com/bitnami/charts
          version: 11.14.2
          chart_pull_secret_ref:
            name: chart-pull
            namespace: default
          container_pull_secret_ref:
            name: container-pull
            namespace: default
      redis:
        helm_chart:
          repo: oci://harbor.yldemotanzu.com/bitnami/charts
          version: 17.10.0
          chart_pull_secret_ref:
            name: chart-pull
            namespace: default
          container_pull_secret_ref:
            name: container-pull
            namespace: default
    policy:
      tuf_enabled: false
    tap_telemetry:
      installed_for_vmware_internal_use: "true"
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: gorkem/namespace-provisioner/namespaces
        url: https://github.com/gorkemozlu/tap-gitops-ri.git
      additional_sources:
      - git:
          ref: origin/main
          subPath: gorkem/namespace-provisioner/resources
          url: https://github.com/gorkemozlu/tap-gitops-ri.git
        path: _ytt_lib/resources
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: grype-airgap-overlay-override
        namespace: tap-install
        create_export: true
